### PR TITLE
Added more information

### PR DESCRIPTION
**Pull request by esilverm**
Added somewhat in depth gallatin query string documentation

### CODE REVIEW

**Comment by esilverm** [comment]
Realized I was committing to the master branch and that probably isnt a good idea

**Comment by esilverm** [comment]
Ok

**Comment by A1Liu** [comment]
lol

**Comment by esilverm** [comment]
help

**Comment by A1Liu** [comment]
lmao

**Comment by A1Liu** [comment]
u did it :D

**Comment by esilverm** [comment]
what a rollercoaster of emotions

**Pull request merged**
