### PR TITLE
Create a page footer view and add multiple flavortexts to it

### PR DESCRIPTION
**Pull request by kburk1997**
Add handlebars template and JS controller for footer text

### CODE REVIEW

**Comment by kburk1997** [comment]
screenshot_2017-02-26_16-23-51
Screenshot

**Comment by copperwater** [comment]
@Bad-Science a few of the flavortexts seem a bit brash or "off" to me on reflection: "a human-haired", "an official dad approved", "better than your mother's", "Clippy's favorite". Also I'm not sure what Marx-rejected is supposed to mean.

Side note: this will close #207.

**Comment by Bad-Science** [comment]
@copperwater Okay let's remove "Human haired" and "Marx rejected". I Like "clippy's favorite" and the mom and dad ones though.

**Comment by kburk1997** [comment]
All changes you suggested are done @Bad-Science

**Pull request merged**
