### PR TITLE
Added animations to the sidebar

### PR DESCRIPTION
**Pull request by Malorn44**
This addresses issue #372 
Wow... been opened since November. Crazy

There are a couple of issues with mobile but it works great on the Desktop version.

### CODE REVIEW

**Comment by Malorn44** [comment]
Meant to put this in a separate PR... but whatever. It's still an animation so it applies. I think I'm going to also disable animations for the sidebar on mobile because they don't work and don't look good anyway. 

So, this PR now addresses issue #442

**Comment by Bad-Science** [comment]
BTW what is the `hamburgers` library used for? Is it needed for the animation?

**Comment by Malorn44** [comment]
Ok. I'll get that done. 
Hamburgers is an open-source library for hamburger menu toggle button animations.

**Comment by Malorn44** [comment]
We can remove any unnecessary files that don't have to do with the specific animation we would want to be using as well. Also, I have no idea how that created a conflict. I literally just changed one of the classes on the sidebar alert.

**Comment by Malorn44** [comment]
I liked it with 600 font weight better than 300. So I changed it. 300 was too hard to see

**Comment by Malorn44** [comment]
I'll resolve conflicts after I install library with npm instead

**Pull request closed without merging**
